# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 662ba039dd50183ef39277cb6ff08730fabeb84c9e26c435d4d4771061acad7b6259042e09368c16c1e113caec6e4d203fa228b57ecc8b59b59aeb63f3d5dcde
  stripe_publishable_key: pk_test_plrMsklylDSMK0Cxv3OqpTFB
  stripe_secret_key: sk_test_SOgXv7fQPmfobUFL9TmNPPrY
test:
  secret_key_base: 602c775a2311a20d8d8b650ffc9263e6d27fe3ef8cc7eb18844222cba7d7e612d6345aacfa54e7ea02ffd2528357a5f5cadc0507bea6a7a4654a24ff12ba5469

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
